# Meta Data for SEO

## Homepage
title = "Nutek Terminal"
titleSeparator = "-"
titleAddition = "The only h@xor tool you will ever need"
description = "Nutek Terminal is a system for building secure apps and assessing security of already working apps. Cybersecurity first class!"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "nutek.neosb.net"
titleHome = "Nutek Terminal"

## Twitter Cards
twitterSite = "@museyoucoulduse"
twitterCreator = "@museyoucoulduse"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Nutek"
schemaAuthor = "Szymon Błaszczyński"
schemaAuthorTwitter = "https://twitter.com/museyoucoulduse"
# schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/buahaha"
schemaLocale = "en-US"
schemaLogo = "logo-nutek.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "nutek.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/museyoucoulduse"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/phoenix-journey/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Phoenix Journey - H@cking 'round the cable. Future is her3 '' Watch it @gain."

# Feed
copyRight = "Copyright (c) 2023 Szymon Bronisław Błaszczyński"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Nutek run scripts, Powershell script that is easy way to run Nutek Terminal! <a class=\"alert-link stretched-link\" href=\"https://github.com/phoenix-journey/nutek-run-scripts/\">Check out GitHub</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/phoenix-journey/phoenix-journey.github.io"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
